name: Tests + Allure Report

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 📥 Код
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🐍 Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      # 📦 зависимости
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 🌐 Chrome
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      # ▶️ тесты
      - name: Run tests
        run: |
          pytest --alluredir=allure-results

      # ☕ Java (нужен для Allure)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 📊 Установка Allure CLI
      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          echo "$(pwd)/allure-2.27.0/bin" >> $GITHUB_PATH

      # 📊 Генерация отчета
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report

      # 🚀 Публикация
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
