name: Tests + Allure Report

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # нужно для gh-pages

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Start mock API
        run: |
          python tests/api/mock_api.py > api.log 2>&1 &
          sleep 3

      - name: Wait for API (hard check)
        run: |
            for i in {1..20}; do
            if curl -f http://localhost:5000/ego18/billing/api/pending_counts; then
            echo "API is ready"
            exit 0
            fi
            echo "Waiting for API..."
            sleep 2
            done
            echo "API failed to start"
            cat api.log
            exit 1

      # ✅ Запуск тестов
      - name: Run tests
        run: |
          pytest --alluredir=allure-results

      # ✅ Установка Java (нужен для Allure)
      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre

      # ✅ Скачивание Allure (фикс версии)
      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
          tar -zxvf allure-2.24.0.tgz
          sudo mv allure-2.24.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # ✅ Генерация отчёта
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      # ✅ Деплой в GitHub Pages
      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
