name: Tests + Allure Report

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #  Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      #  Установка зависимостей
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      #  Установка Chrome (для Selenium)
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      #  Запуск тестов
      - name: Run tests
        run: |
          pytest --alluredir=allure-results

      #  Генерация Allure отчета
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report

      #  Публикация в GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
